ALTER TABLE "8fold_test"."User"
ADD COLUMN IF NOT EXISTS "accountStatus" TEXT DEFAULT 'ACTIVE' NOT NULL,
ADD COLUMN IF NOT EXISTS "suspendedUntil" TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS "deletionReason" TEXT NULL;

