export const AuthErrorCodes = {
  // Authentication
  AUTH_CONFIG_MISSING: "AUTH_CONFIG_MISSING",
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_INVALID_ISSUER: "AUTH_INVALID_ISSUER",
  AUTH_INVALID_AUDIENCE: "AUTH_INVALID_AUDIENCE",
  AUTH_CLERK_VERIFICATION_FAILED: "AUTH_CLERK_VERIFICATION_FAILED",

  // Identity mapping
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ROLE_NOT_ASSIGNED: "USER_ROLE_NOT_ASSIGNED",
  USER_SOFT_DELETED: "USER_SOFT_DELETED",
  USER_DUPLICATE_MAPPING: "USER_DUPLICATE_MAPPING",

  // Authorization
  ROLE_MISMATCH: "ROLE_MISMATCH",
  ROLE_NOT_PERMITTED: "ROLE_NOT_PERMITTED",
  ROLE_IMMUTABLE: "ROLE_IMMUTABLE",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
} as const;

export type AuthErrorCode = (typeof AuthErrorCodes)[keyof typeof AuthErrorCodes];
