import { boolean, doublePrecision, integer, jsonb, text, timestamp } from "drizzle-orm/pg-core";
import { dbSchema } from "./_dbSchema";

export const contractorProfilesV4 = dbSchema.table("contractor_profiles_v4", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email"),
  avatarUrl: text("avatar_url"),
  contactName: text("contact_name").notNull(),
  phone: text("phone").notNull(),
  businessName: text("business_name").notNull(),
  businessNumber: text("business_number"),
  startedTradeYear: integer("started_trade_year"),
  startedTradeMonth: integer("started_trade_month"),
  acceptedTosAt: timestamp("accepted_tos_at", { mode: "date" }),
  tosVersion: text("tos_version"),
  formattedAddress: text("formatted_address"),
  yearsExperience: integer("years_experience"),
  city: text("city"),
  postalCode: text("postal_code"),
  countryCode: text("country_code"),
  tradeCategories: jsonb("trade_categories").notNull(),
  serviceRadiusKm: integer("service_radius_km").notNull(),
  homeLatitude: doublePrecision("home_latitude").notNull(),
  homeLongitude: doublePrecision("home_longitude").notNull(),
  stripeConnected: boolean("stripe_connected").notNull().default(false),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});
